maintainer       "Pierre Riteau"
maintainer_email "priteau@uchicago.edu"
license          "Apache 2.0"
description      "Installs/Configures nimbusautoscale"
version          "0.0.1"
depends          "virtualenv"
